name: CI/CD for .NET & Angular

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build & Test .NET API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

  build-frontend:
    name: Build Angular App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11
      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --if-present
